name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run tests with race detector
        run: go test -race -v ./...
